### ISSUE TITLE
Video playback freezes when this module is installed

### ISSUE THREAD

**Issue by michaelphagen** [Alcatraz323/audiohq_module#1]
On an ROG Phone II, the phone freezes (unresponsive to input and video and audio both stop and start repeatedly) when playing video with this module installed. Applications that only play audio (eg. spotify) are unaffected by this bug, and additionally per-app audio controls work properly

**Comment by Alcatraz323** [comment]
DO NOT FLASH ON HEAVY MODIFIED SYSTEM

**Comment by michaelphagen** [comment]
The version of android that Asus uses is not generally considered to be a heavily modified version. Could you define "heavy modified system" more clearly?
