### ISSUE TITLE
ok caused bootloop on my samsung device

### ISSUE THREAD

**Issue by AbhimanyuAryan** [Alcatraz323/audiohq_module#12]
I have an old Samsung device SM-G610F(India) rooted with Magisk. Tried installing module with Magisk and caused bootloop ;( 

From the commit history, the project looks pretty active. Can you help me debug the problem? Really want this module to work. Some apps are just beyond irritating. Must shut them up 🔢 

Firmware: https://www.sammobile.com/samsung/galaxy-j7-prime/firmware/SM-G610F/INS/download/G610FXXS1CTD1/348733/

**Comment by lnro** [comment]
I thought it was made clear that this module had the possibility to cause bootloops on OEM customized roms like Samsung's OneUI/Touchwiz? 
![image](https://user-images.githubusercontent.com/63747539/160196725-64c929dd-7bbc-48a8-952f-3c102116c398.png)

**Comment by AbhimanyuAryan** [comment]
Yaa re-flashed
