### ISSUE TITLE
No-APK only allows on or off

### ISSUE THREAD

**Issue by lauris0910** [Alcatraz323/audiohq_module#18]
Hello, when i tried to use the No-Apk variant, it seems that i can only turn individual app sounds either On or Off but not directly change the volume for the specific app, could you suggest what i should do to fix this? My device is Xiaomi Redmi Note 7 (Lineage OS Rom).

**Comment by Alcatraz323** [comment]
no apk means no controller software, install by yourself
https://github.com/Alcatraz323/audiohq_md2/releases
