### ISSUE TITLE
audioserver error

### ISSUE THREAD

**Issue by Ahtlon** [Alcatraz323/audiohq_module#2]
This error appears when trying to start audioserver.
`CANNOT LINK EXECUTABLE "/system/bin/audioserver": cannot locate symbol "_ZN7android10AudioMixer12mUIDRCEnableE" referenced by "/system/lib/libaudioflinger.so"`

**Comment by Ahtlon** [comment]
edit: turns out I have no idea what I am talking about

**Comment by Alcatraz323** [comment]
this error may come from you downloaded the oldest module from my github.io website, you may try this repo's release
