### ISSUE TITLE
Does this work on OnePlus OxygenOS?

### ISSUE THREAD

**Issue by santient** [Alcatraz323/audiohq_module#20]
I'm thinking of flashing this on my rooted OnePlus with OxygenOS (api 30) but I was wondering if anyone has tried this yet / has any info as to whether this will work or soft brick.

**Comment by re-unknown** [comment]
Oxygen OS is a fairly custom OS and AudioHQ will probably not work because it is incompatible with the Oxygen OS system UI, as far as I have tried.

**Comment by Alcatraz323** [comment]
Yes for most, but Snapdragon 870 device is a exception
