### ISSUE TITLE
Can't have 2 apps Playing audio at same time 

### ISSUE THREAD

**Issue by kmjsmith** [Alcatraz323/audiohq_module#27]
Hi I have a pixel 7 and for some reason playimg Spotify and VLC or plex any the same time doesn't work the phone will only play one audio source I have the app installed correctly permissive mode on se Linux and the audio hq foreground banner enabled.

**Comment by Alcatraz323** [comment]
Use a permission app like "AppOps" to disable the audio focus permission on both app or find something like "playing same time" in those app's settings . This software don't provide playing same time control
