### ISSUE TITLE
Doesn't work on Xiaomi Redmi 6 4/64 gb phone

### ISSUE THREAD

**Issue by Foxydroid** [Alcatraz323/audiohq_module#5]
Endless loading in bootanimation

**Comment by Foxydroid** [comment]
SELinux Status: Permisive
Xiaomi Redmi 6
MIUI 11.0.4.0 Global
Android 9 32 bit
App version: 0.8_2020_12_13_stable_7_anniversary_aa1c37f
Magisk version 22.0
Module version: rel-0.91-20201126

**Comment by Alcatraz323** [comment]
mtk processor not supported
